name: Alamo Alert
on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Chrome 140 + ChromeDriver 140
        run: |
          mkdir -p /tmp/chrome-downloads
          cd /tmp/chrome-downloads

          wget -q https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/linux64/chrome-linux64.zip
          unzip -q chrome-linux64.zip
          sudo mv chrome-linux64/chrome /usr/bin/google-chrome
          sudo chmod +x /usr/bin/google-chrome

          wget -q https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/linux64/chromedriver-linux64.zip
          unzip -q chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

          google-chrome --version
          chromedriver --version

      - name: Install Selenium
        run: pip install selenium

      - name: Run Alamo Alert
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python alamo_alert.py
