name: Alamo Alert
on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Chrome + webdriver-manager
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium webdriver-manager

      - name: Run Alamo Alert
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python alamo_alert.py
